### ISSUE TITLE
Categorize documentation under programmer interface

### ISSUE THREAD

**Issue by kunaltyagi** [freeCodeCamp/devdocs#1465] opened 2021-01-20 09:02 UTC
Interface: can be a language (like Python or JS), or program API (eg: Docker) or something else

Sometimes, I feel like finding what other popular and good documentation are there for certain interface. This will help collapse interfaces that aren't needed and focus on finding documentation in the ones that are available.

Manually typing to enable takes more effort that scrolling and reading the alphabetized list quickly. Unfortunately, different language based libraries are mixed together. Some of them are polyglot libraries, making it harder to guess if they'd have you interface, resulting in decreased happiness.

This is vital when I move to a new code-base in a language that I haven't used for a while. Grok around the code for a while, get the documentations for all the weird keywords that feel vaguely familiar and then get to work :)

**Comment by simon04** [comment] 2021-01-20 09:24
Duplicate of https://github.com/freeCodeCamp/devdocs/issues/4

**Closed by simon04** 2021-01-20 09:24 UTC
