### ISSUE TITLE
Add feacture to import/export locally installed docs

### ISSUE THREAD

**Issue by Bam92** [freeCodeCamp/devdocs#1205] opened 2020-04-02 13:04 UTC
`Devdocs` is a great tool, it helps me so much especially when I cannot access the Internet. But I find some limitations with the tool. I cannot backup my installations and restore them in any other browser or computer.

**Comment by ymeine** [comment] 2020-04-03 09:17
You should have an `export` and `import` button in the settings page: https://devdocs.io/settings

**Comment by simon04** [comment] 2021-04-22 18:20
Duplicate of #336

**Closed by simon04** 2021-04-22 18:20 UTC
Labels: feature
