### ISSUE TITLE
Pandas documentation is outdated

### ISSUE THREAD

**Issue by BlueskyFR** [freeCodeCamp/devdocs#1245] opened 2020-06-17 08:10 UTC
Hi!

I can see that the current version of the pandas documentation is 0.25 but the official latest version is 1.0.3.
Is there any way someone can update it?

Thanks in advance.

**Comment by bilderbuchi** [comment] 2020-08-02 09:16
This is a duplicate of #1206.

**Comment by simon04** [comment] 2020-11-06 19:31
Duplicate of #1206

**Closed by simon04** 2020-11-06 19:31 UTC
Labels: docs/update
