### ISSUE TITLE
Documentation: select latest version (forever)

### ISSUE THREAD

**Issue by kunaltyagi** [freeCodeCamp/devdocs#1464] opened 2021-01-20 08:44 UTC
Is it possible to have a pinned documentation, eg: Python 3.6 as well as a latest documentation: Python-latest (could be 3.8 or 3.9 for all I care)?

**Comment by simon04** [comment] 2021-04-29 20:27
Duplicate of https://github.com/freeCodeCamp/devdocs/issues/744

**Closed by simon04** 2021-04-29 20:27 UTC
Labels: feature
