### ISSUE TITLE
Firefox no search result, CSP error in console

### ISSUE THREAD

**Issue by spumer** [freeCodeCamp/devdocs#1035] opened 2019-08-06 07:34 UTC
I can't search docs from Firefox
![изображение](https://user-images.githubusercontent.com/735150/62520004-13bebe80-b846-11e9-9550-8acf02a376c6.png)

I try to use offload mode, but this not helps

![изображение](https://user-images.githubusercontent.com/735150/62520112-4c5e9800-b846-11e9-9fda-3d841f6b5f15.png)

In console log i see that:

```
Content Security Policy: Параметры страницы заблокировали загрузку ресурса eval («script-src»).
Content Security Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). devdocs.io:1:1
Не удалось загрузить «https://devdocs.io/docs/django~2.1/index.json?1534717304». ServiceWorker передал promise в FetchEvent.respondWith(), который отвергнул его с ошибкой «TypeError: NetworkError when attempting to fetch resource.».
Не удалось загрузить «https://devdocs.io/docs/python~3.7/index.json?1538925436». ServiceWorker передал promise в FetchEvent.respondWith(), который отвергнул его с ошибкой «TypeError: NetworkError when attempting to fetch resource.».
​

**Comment by jmerle** [comment] 2019-08-06 08:05
Did you by any chance clear the service worker cache recently?

**Comment by spumer** [comment] 2019-08-06 08:46
Manually? No. I'm using docs for python 3.6 for a long time, but when i try set python 3.6 or any other i was failed.

Do you recommend clear the service worker cache?

**Comment by jmerle** [comment] 2019-08-06 09:27
No, apparently I found a different bug (which is only triggered if you manually clear the cache). I'm still not sure what's going on because I can't reproduce your bug.

Can you try performing the same actions in an incognito session without extensions? I'm wondering whether you might have an extension running that modifies our CSP in some way.

**Comment by spumer** [comment] 2019-08-06 12:06
Yea, thats helps! Without addons all works fine.

Tampermonkey - that addons change CSP, when i disable only that extension no errors in console

**Comment by jmerle** [comment] 2019-08-06 12:10
Great! Closing this as there's nothing wrong with DevDocs itself.

**Closed by jmerle** 2019-08-06 12:10 UTC
