### ISSUE TITLE
Searching for enabled "Ruby" shows "RethinkDB ruby"

### ISSUE THREAD

**Issue by evmorov** [freeCodeCamp/devdocs#1516] opened 2021-04-02 12:54 UTC
## OS information

macOS, Chrome 89

## Steps to reproduce

- Enable Ruby
- Don't enable RethinkDB
- Write "ruby" into the search field

### Actual result

DevDocs suggests not installed "RethinkDB ruby"

### Expected result

DevDocs suggests installed Ruby so I can press Tab and search within.

## More resources

---

![image](https://user-images.githubusercontent.com/1059480/113417218-9dcc7b00-93cb-11eb-8f36-32243bfcc711.png)

---

![image](https://user-images.githubusercontent.com/1059480/113417240-a755e300-93cb-11eb-916d-10ba33dcb952.png)

**Comment by ojeytonwilliams** [comment] 2021-04-05 15:55
Hi @evmorov, I see what you mean about the search order, but tab works as expected for me:
![Ruby](https://user-images.githubusercontent.com/15801806/113594212-ab863880-9637-11eb-9877-2d4941762284.gif)

In the gif I tabbed at 'rub', but everything from 'r' to 'ruby' works as expected.

If possible could you try using a different browser and see if you encounter the issue?

**Comment by evmorov** [comment] 2021-04-05 16:08
> If possible could you try using a different browser and see if you encounter the issue?

Initially, I saw the issue on my wife's laptop. I reproduced the problem on my laptop with no problem.

I think when you typed `ru`, `Ruby` should have been suggested instead of not installed `Rust`. It makes no sense to suggest something not installed when you have something installed that matches.

Also, you can notice that I (and my wife) have `Ruby` enabled not `Ruby 3` like you. It can be the difference.

**Comment by evmorov** [comment] 2021-04-05 16:13
> Also, you can notice that I (and my wife) have Ruby enabled not Ruby 3 like you. It can be the difference.

It's not:

![ruby](https://user-images.githubusercontent.com/1059480/113596452-ffe2e580-9642-11eb-956f-186216e7e8bc.gif)

**Comment by ojeytonwilliams** [comment] 2021-04-05 16:25
> I think when you typed ru, Ruby should have been suggested instead of not installed Rust. It makes no sense to suggest something not installed when you have something installed that matches.

As I understand it, the rationale is just that until the user indicates that they're only interested in Ruby (by pressing tab) it should not make assumptions about their intent.

That said, if tab is not selecting Ruby, that's definitely a bug.  Do you have steps to reproduce that? I haven't been able to.

**Comment by evmorov** [comment] 2021-04-05 17:22
After pressing Tab it actually chooses Ruby. Looks weird to me. I've recorded the video in incognito mode:

1. Disable all the languages except of Ruby
2. Type `ruby`
3. See that `RethinkDB ruby` is shown on the top instead of only installed `Ruby`
4. Press `Tab`
5. Ruby is selected but the cursor was on `RethinkDB ruby`

I expect on step 3 to see `Ruby` instead of `RethinkDB ruby` on the top. 

![ruby2](https://user-images.githubusercontent.com/1059480/113603084-25c0b800-964c-11eb-987b-c241e89ca767.gif)

**Comment by ojeytonwilliams** [comment] 2021-04-05 17:40
Thanks for taking the time to record the gif, that definitely helps.

Admittedly I'm relatively new to the project, but what you've detailed here is how I expect it to behave.  If you only want to see Ruby results, you can enable only that and type `r` `tab` and then all the results will from Ruby.

Having said all that, there's room for disagreement here, so we can leave this issue open and see if more people find this behaviour frustrating.

**Comment by j-f1** [comment] 2021-04-05 17:46
I think it would be good to provide a hint for users — maybe there should be an indicator like Chrome has? 
<img width="669" alt="Screenshot_2021-04-05 13 46 06" src="https://user-images.githubusercontent.com/25517624/113605888-47527d00-9615-11eb-9177-b188948c46c5.png">

**Comment by ojeytonwilliams** [comment] 2021-04-05 17:49
I rather like that idea.  The initial placeholder is good, but if something like "Press tab to search Ruby 3" appeared as you typed, that would be a nice addition.

**Comment by MasterEnoc** [comment] 2021-04-06 05:36
@evmorov The `tab` only works with the enabled docs but the search bar searchs in all the available docs. The search bar is going to show the closest match of what you are searching and the `tab` is going the select the closest match in the enabled docs.  

Look how this happen to me with a different doc: 
![sc](https://user-images.githubusercontent.com/52229226/113663430-41858780-9667-11eb-8081-92da83becd36.gif)

This could be improved but the enabled docs are going to have priority in the search bar and I do not if this behaviour is wanted.

**Comment by evmorov** [comment] 2021-04-06 06:49
Thanks! So it's a UX problem or the issue can be closed then.

**Comment by MasterEnoc** [comment] 2021-04-07 07:10
What do you think @ojeytonwilliams @j-f1?

**Comment by ojeytonwilliams** [comment] 2021-04-07 07:36
I think we can close this, since we've discussed it pretty thoroughly.  What I'll do is create a new 'help wanted' issue to track Jed's idea.

**Closed by ojeytonwilliams** 2021-04-07 07:36 UTC
Labels: bug
