### ISSUE TITLE
"Install all" errors for each documentation

### ISSUE THREAD

**Issue by lifetin** [freeCodeCamp/devdocs#1263] opened 2020-08-21 02:13 UTC
![33](https://user-images.githubusercontent.com/10474968/90844649-fb5d0b80-e396-11ea-9e04-4d893f54fd48.png)
![44](https://user-images.githubusercontent.com/10474968/90844651-fc8e3880-e396-11ea-871a-d8c91d9d7785.png)

**Comment by djndl1** [comment] 2020-10-11 12:46
One of the most painful things living in China is having a hard time trying to use any foreign web service due to slow network.

**Comment by simon04** [comment] 2020-11-06 19:30
Duplicate of #1260

**Closed by simon04** 2020-11-06 19:30 UTC
