### ISSUE TITLE
cannot open on chrome 73

### ISSUE THREAD

**Issue by zzjin** [freeCodeCamp/devdocs#959] opened 2018-12-18 05:54 UTC
When upgrade to chrome 73,devdocs cannot open.
reloading resetting do not work.
console shows:
```
Uncaught TypeError: Illegal constructor
    at new t (application-0907855419e90a5c1923cd6a6174aa1cabca1c0cddbd9f06f003d402fa28c23d.js:4068)
    at Object.init (application-0907855419e90a5c1923cd6a6174aa1cabca1c0cddbd9f06f003d402fa28c23d.js:3316)
    at HTMLDocument.t (application-0907855419e90a5c1923cd6a6174aa1cabca1c0cddbd9f06f003d402fa28c23d.js:7133)
```

which seems show that `this.store = new CookieStore(),` is broken?

**Comment by Thibaut** [comment] 2018-12-18 16:40
Duplicate of #932

**Closed by Thibaut** 2018-12-18 16:40 UTC
