### ISSUE TITLE
PWA with ServiceWorker

### ISSUE THREAD

**Issue by JasMich** [freeCodeCamp/devdocs#894] opened 2018-10-10 15:03 UTC
It would be nice offering a JavaScript ServiceWorker for making the Website fully installable and Working like a native App (PWA) It would be more comfortable specially on handheld devices.

**Comment by j-f1** [comment] 2018-10-10 15:13
Duplicate of #774

**Comment by j-f1** [comment] 2018-10-10 15:14
You should be able to add the DevDocs website to your home screen already.

**Closed** 2018-10-10 15:13 UTC
