### ISSUE TITLE
datetime link to mozzila is broken

### ISSUE THREAD

**Issue by AbhinavAchha** [freeCodeCamp/devdocs#1523] opened 2021-04-19 14:04 UTC
The link to datetime attribute in html located in https://devdocs.io/html-attributes/ is broken.

please update to the correct link which is https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

**Comment by ojeytonwilliams** [comment] 2021-04-19 15:30
Thanks for the report @AbhinavAchha.  The problem is that the page this is sourced from, https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes, has a broken link to datetime.  The correct link is https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#attr-datetime

@freeCodeCamp/devdocs any idea how easy it would be to create an exception in the scraper?

**Comment by j-f1** [comment] 2021-04-19 16:08
This should probably be fixed on MDN’s side (see issue linked above)

**Comment by simon04** [comment] 2021-05-06 21:09
Fixed on MDN. Fixed with the recent doc updates, see #1514.

**Closed by simon04** 2021-05-06 21:09 UTC
Labels: docs/bug
