### ISSUE TITLE
MDN Docs with interactive examples auto-focus on example code, breaking keyboard navigation 

### ISSUE THREAD

**Issue by sushant-j** [freeCodeCamp/devdocs#779] opened 2018-03-28 12:27 UTC
**Description:** 
When referring MDN docs with new, [interactive examples](https://hacks.mozilla.org/2018/03/bringing-interactive-examples-to-mdn/), keyboard focus is automatically switched to the example code. This makes navigating with keyboard shortcuts impossible.

**Steps to reproduce:**
1. Search for any CSS property which has an interactive example on MDN docs.
[E.g. background-size, transform, etc.]
2. Press enter to open the docs in right, preview pane for Devdocs.
3. Observe that keyboard focus is now on interactive example code, and navigation in left pane is not possible.

**Environment**
- OS: Linux Ubuntu 16.04.4
- Browser: Chrome - Version 65.0.3325.146 (64-bit)

**Comment by jmerle** [comment] 2018-10-06 15:56
Fixed in mdn/interactive-examples#1158. This can be closed.

**Comment by jmerle** [comment] 2018-10-07 11:14
I don't think the MDN docs need an update to fix this issue. DevDocs shows the interactive examples inside iframes, so DevDocs automatically uses the latest version of the source of the interactive examples, which now comes without the auto-focus thing.

I can't really explain it, but just try to reproduce the issue and you'll see that it's gone.

**Comment by j-f1** [comment] 2018-10-07 12:42
Thanks for clarifying @jmerle!

**Closed** 2018-10-07 12:41 UTC

**Comment by vaaski** [comment] 2021-06-08 17:17
this issue seems to be back, it autofocuses the code block on [this](https://devdocs.io/javascript/global_objects/function/call) page, breaking keyboard navigation.

not sure if it's related to the same mdn thread so i'm pining here.
