### ISSUE TITLE
Move from `applicationCache` to using `ServiceWorkers`

### ISSUE THREAD

**Issue by E314c** [freeCodeCamp/devdocs#818] opened 2018-06-06 15:08 UTC
It appears that devdocs is currently using `window.applicationCache` to provide some of it's offline loading capability.

[MDN notes that this is deprecated and no longer part of the web standards](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache)

The alternative is to move to [ServiceWorkers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers). 
[CanIUse](https://caniuse.com/#feat=serviceworkers) indicates general availability for modern browsers.

This will require serving a serviceWorker file from the server, instead of serving the `cache manifest` file.

**Comment by j-f1** [comment] 2018-06-06 15:44
Duplicate of #774.

**Closed** 2018-06-06 15:44 UTC

**Comment by E314c** [comment] 2018-06-06 16:18
sorry, I'd done a search of `is:issue is:open serviceworker` and it didn't turn up any results.
