### ISSUE TITLE
devdocs.io does not work on chromebook

### ISSUE THREAD

**Issue by oyiptong** [freeCodeCamp/devdocs#1018] opened 2019-06-26 20:27 UTC
Opening devdocs.io on a chromebook yields a javascript error:
```
application-3d849e25dd9d76c90a2be3c29cd33956b832f156e89f1ceeadc018323c3bcc81.js:4068
Uncaught TypeError: Illegal constructor
    at new t (application-3d849e25dd9d76c90a2be3c29cd33956b832f156e89f1ceeadc018323c3bcc81.js:4068)
    at Object.init (application-3d849e25dd9d76c90a2be3c29cd33956b832f156e89f1ceeadc018323c3bcc81.js:3316)
    at HTMLDocument.t (application-3d849e25dd9d76c90a2be3c29cd33956b832f156e89f1ceeadc018323c3bcc81.js:7133)
```
![image](https://user-images.githubusercontent.com/9365/60212388-00b3da00-9816-11e9-8327-8db93126ee23.png)

**Comment by j-f1** [comment] 2019-08-13 14:15
This is a duplicate of https://github.com/freeCodeCamp/devdocs/issues/932, which has [been fixed](https://github.com/freeCodeCamp/devdocs/issues/932#issuecomment-518000613):

> Fixed in b23b81e by renaming our CookieStore to CookiesStore.

**Closed by j-f1** 2019-08-13 14:15 UTC
