### ISSUE TITLE
Add math rendering library

### ISSUE THREAD

**Issue by scherepn** [freeCodeCamp/devdocs#1442] opened 2020-12-23 19:46 UTC
The documentation set `scikit-learn` has TeX mathematical formulas that are rendered client-side.

Look at https://devdocs.io/scikit_learn/modules/clustering page under the first heading "2.3.2. K-means" to see unrendered TeX mathematics code. Compare https://scikit-learn.org/0.23/modules/clustering.html to see what the rendered output looks like.

The source documentation uses (MathJax)[https://www.mathjax.org/] to render these.

**Comment by simon04** [comment] 2020-12-23 20:07
Duplicate of #1264

See also https://github.com/freeCodeCamp/devdocs/issues/750#issuecomment-730268030

**Closed by simon04** 2020-12-23 20:07 UTC
