### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by alexch** [freeCodeCamp/devdocs#788] opened 2018-04-06 16:34 UTC
This is a placeholder issue for a discussion around how to automate DevDocs and spread the workload among several volunteers rather than a single @Thibaut .

Feature ideas:

On a cloud server instance, e.g. Travis or AWS or Heroku:

- [ ] periodic re-scraping of all remote doc sets
- [ ] periodic re-downloading of archived doc sets
- [ ] periodic re-downloading and re-generating of rdoc
  * are there any other doc sets that need to be generated locally, not 

Results from above (including diffs between the previous successful run and the current one) would be emailed to a list and/or published to an admin site or gist; a set of QA volunteers would look over the diffs and results and report errors etc. as GitHub issues, then dev volunteers would continuously make PRs based on those issues.

- [ ] automated scraper would need to save its results somewhere, so a dev could reproduce the issue without needing to hit the network again (and again)

- [ ] make sure process exit codes are valid (0 = no errors, >1 = errors) so the results would only be emailed if something needs attention

**Comment by simon04** [comment] 2020-11-17 18:32
Thank you, @alexch, for you thoughts and suggestions. We've been discussing this topic recently. The discussion moved to a separate issue #1306 (unfortunately, we forgot this one). Therefore, I'm closing this one…

Duplicate of #1306

**Closed by simon04** 2020-11-17 18:32 UTC

**Comment by ojeytonwilliams** [comment] 2020-11-18 09:29
Apologies, @alexch, I created that in part to keep a record of a Gitter comment by Jasper - I wasn't thinking about duplicates.
