### ISSUE TITLE
Anchors are broken in mobile mode

### ISSUE THREAD

**Issue by TiZ-EX1** [freeCodeCamp/devdocs#769] opened 2018-03-20 20:51 UTC
I use devdocs.io in a tiny Firefox window so it ends up in mobile mode. Some parts of documentation have faulty shortcuts in this mode.

To reproduce:
1. Firefox on Android or small Firefox window
2. Enable docs for Crystal
3. Find a method you want to learn about, like Enumerable's reduce. Click on the link.
4. Get sent to the top of the Enumerable page instead of the specific method.
5. That's fine, scroll down to the table of contents and click #reduce there.
6. Nothing happens.

Expected result:
Get sent to the part of the page that explains the specific method. Also, for the table of contents links to do the same thing. These two things may be related.

This works fine in desktop mode, not sure why.

**Comment by Yanpas** [comment] 2018-04-16 20:47
Same story. It is reproducible with desktop chrome dev tools if you select any mobile device in toolbar

**Comment by Yanpas** [comment] 2018-04-16 21:26
Mobile version differs from desktop one and the bug exists in any browser in mobile version.

I have inspected the cause of it in the dev tools and it is "click" event listener belonging Window object. Removing it solves the issue.
![image](https://user-images.githubusercontent.com/7345761/38836158-e3cb921c-41d5-11e8-8ebd-a3ff469250e8.png)

**Comment by Yanpas** [comment] 2018-04-16 21:34
That event listener seems to belong to some tracking platform `https://secure.gaug.es/track.js` (needless for end user) since errors in js console disappeared

**Comment by TiZ-EX1** [comment] 2018-04-17 14:26
So what's the fix on the end user side? As in, what kind of userscript can I apply to fix it until the actual fix comes down the pipe? It looks like just blocking secure.gaug.es in my hosts file isn't enough to fix it.

**Comment by Yanpas** [comment] 2018-04-17 14:46
I'm the end user too and didn't find a solution yet

**Comment by TiZ-EX1** [comment] 2018-04-17 15:51
I'm pretty sure the tracking platform isn't the culprit. In addition to trying to block the tracker from my workbox explicitly, my laptop blocks it implicitly due to tracking protection. The script isn't being loaded. Allowing it to be loaded makes no difference. So it's probably some other faulty thing from the site.

So is it a thing of where if you remove the event listener from your development console, anchors start working again? I'm trying to think of how I would remove it in Firefox, and then how I would patch it with Tampermonkey.

**Comment by Yanpas** [comment] 2018-04-17 16:07
Yes, after removing one concrete event-listener anchors start working.

I see the following options:
* load full desktop version of a site
* execute somehow js-script after page load which removes that listener (maybe some extension exists)

Blocking that domain would only harm since you will get js-exceptions of request execution failures.

**Comment by Thibaut** [comment] 2018-07-09 02:13
Fixed by #821.

**Closed by Thibaut** 2018-07-09 02:13 UTC
Labels: bug
