### ISSUE TITLE
Cannot install DOM

### ISSUE THREAD

**Issue by wodecs** [freeCodeCamp/devdocs#1275] opened 2020-09-14 14:08 UTC
Cannot install DOM (34 MB). Others are good to go. Just said "Error". I don't know how to fix it. Do you have the same problem?

**Comment by mortalis13** [comment] 2020-09-25 11:43
What's your environment?
Android/Windows/Chrome/Firefox?

**Comment by wodecs** [comment] 2020-09-26 05:23
> What's your environment?
> Android/Windows/Chrome/Firefox?

Windows 10, 32 bit, Chrome browser

**Comment by mortalis13** [comment] 2020-09-28 08:43
Check if the Console shows any related errors.
I tried to download DOM from Chrome and it works fine, maybe there was a connection timeout and it could not download the whole package.

**Comment by roimergarcia** [comment] 2020-10-04 20:39
I've have the same Issue for a couple of months. In Firefox (current version), on Windows 10 64 bit. I finally could install CSS (12.5 MB) after having that same error two times, and other (smaller) docs with no issues. 
In the console I see this message (in Spanish):
`Fallo al cargar 'https://docs.devdocs.io/dom/db.json?1543157862'. Un ServiceWorker ha interceptado la solicitud y encontrado un error inesperado.`
Translation: 
`Fail to load 'https://docs.devdocs.io/dom/db.json?1543157862'. A ServiceWorker has intercepted the request and has found an unexpected error.`
In the network tab there is a single request to `https://docs.devdocs.io/dom/db.json?1543157862=` , it ends with a 200 OK, but only sends around 9,93 MB with the message "The answer has been truncated".

**Comment by mortalis13** [comment] 2020-10-05 12:49
I tried to Intall/Uninstall the DOM a couple of times without errors.

![image](https://user-images.githubusercontent.com/10464927/95081058-49e12200-0719-11eb-9fdb-0a74f305fd6f.png)

The Response tab also shows **"Response has been truncated"**, so it's just the Network tab cannot load the whole JSON, or truncates it.

I suppose your **Headers -> Transferred** value is less than **32.42 MB**.

Try to open the `https://docs.devdocs.io/dom/db.json?1543157862` in another tab, download it with `wget` to see if it downloads the entire file.

**Comment by mortalis13** [comment] 2020-10-05 12:55
Maybe there's a way to add a timeout for the **ServiceWorker** `fetch`.

**Comment by roimergarcia** [comment] 2020-10-06 02:11
I tried to open https://docs.devdocs.io/dom/db.json?1543157862 directly in a browser tab and could download the whole json file, 32,42 MB, but it took a while to download since my internet connection is slow. I guess the problem is that the connection to devdocs takes too long that the service just timeouts before finishing. 
Then I tried to install it again, but then it failed after 14,68MB, so I'm almost sure the problem is related to the download time.

**Comment by wodecs** [comment] 2020-10-11 03:07
I can install it now. I don't know why

**Comment by wodecs** [comment] 2020-10-11 03:08
> I tried to open https://docs.devdocs.io/dom/db.json?1543157862 directly in a browser tab and could download the whole json file, 32,42 MB, but it took a while to download since my internet connection is slow. I guess the problem is that the connection to devdocs takes too long that the service just timeouts before finishing.
> Then I tried to install it again, but then it failed after 14,68MB, so I'm almost sure the problem is related to the download time.

Maybe the server's problem

**Closed** 2020-10-11 03:09 UTC
