### ISSUE TITLE
Can't type ? on search bar.

### ISSUE THREAD

**Issue by devbapidey** [freeCodeCamp/devdocs#1470] opened 2021-01-29 07:19 UTC
The default '?' symbol is occupied for devdocs help, So while searching in devdocs and typing the ? symbol typing not happens. So I recommended to not fire keyup event for ? when search box is selected.

**Comment by simon04** [comment] 2021-01-29 07:21
Duplicate of #733

**Closed by simon04** 2021-01-29 07:21 UTC
