### ISSUE TITLE
Allow custom documentation packages?

### ISSUE THREAD

**Issue by Eximius** [freeCodeCamp/devdocs#1020] opened 2019-07-05 21:08 UTC
Would it be too difficult to allow to enable documentation available at an url? Say I compiled my own little package and had it hosted somewhere, I could just add it.

This idea goes in line with https://github.com/freeCodeCamp/devdocs/issues/336

**Comment by jmerle** [comment] 2019-07-06 17:03
I don't exactly understand what you're asking for. Could you be more clear in what you would like to be possible?

**Comment by Dadsam902** [comment] 2019-07-28 00:36
Maybe a creating of custom documentation. make by "User". possible using Markdown

**Comment by simon04** [comment] 2019-08-08 15:37
Might be a duplicate of #295.

**Comment by jmerle** [comment] 2019-08-08 15:43
I see #295 as the ability to add custom things using `iframe`'s or similar (like gists and other websites), where-as this issue sounds more of a request to make it possible to integrate externally hosted scraped documentation into the interface hosted on devdocs.io.

@Eximius can you be more clear in your request please?

I'm attaching the needs-info label so it auto-closes in 30 days if there is no response.

**Closed** 2020-02-23 10:44 UTC
Labels: needs-info
