### ISSUE TITLE
JavaScript Error when attempting to open Custom CSS

### ISSUE THREAD

**Issue by Nabawe** [freeCodeCamp/devdocs#1766] opened 2022-06-17 16:30 UTC
Hi I hope I am not making a mistake posting this here.

# Bug report
A JavaScript error ocurred in the main process
Uncaught Exception
TypeError shell.openItem is not a function.

## OS information
Windows 10 64bits
Desktop App DevDocs-Setup-0.7.2.exe

## Steps to reproduce
Uninstalled Old DevDocs. (I believe preferences didn't clean since it kept previous selections and dark mode on).
Installed New Ver.
Preferences > Custom CSS

Additionally if some one is so kind as to point me where can I find the docs to use Custom CSS on the desktop app I would be thankful.

![image](https://user-images.githubusercontent.com/11269209/174338570-eda5e0ae-a9ef-47f5-a556-6cccdcd5c1c3.png)

**Comment by simon04** [comment] 2022-07-15 19:52
Duplicate of https://github.com/egoist/devdocs-desktop/issues/162

**Closed by simon04** 2022-07-15 19:52 UTC
Labels: bug
