### ISSUE TITLE
Group documentation by language

### ISSUE THREAD

**Issue by vladanghene** [freeCodeCamp/devdocs#1017] opened 2019-06-21 15:38 UTC
Hi,
So this is just an idea but I'd very much like to see (help) this happen: language categories as namespaces (or subdomains or tags or topics) in which we can add documentation for libraries -- this is actually really useful since all of the libraries have scattered and non uniform docsets.

**Comment by simon04** [comment] 2020-11-17 18:33
Duplicate of #4

**Closed by simon04** 2020-11-17 18:33 UTC
Labels: feature
